#!/usr/bin/python

# Written by zippynk on BitBucket. https://bitbucket.org/zippynk/jumblecipher
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from jumblecipher import splitEncodedNumbers
encodedPhrase = raw_input("Encoded Phrase? ")
print splitEncodedNumbers(encodedPhrase)
